language: python
python:
- 2.7

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-dbus python-bluez
- pidof dbus-daemon || dbus-daemon --system --fork

# pip cannot install python-dbus: https://bugs.freedesktop.org/show_bug.cgi?id=55439
install: pip install httpretty

script:
- pep8 --max-line-length=120 --exclude=StaticData.py .
- nosetests

notifications:
  irc: "chat.freenode.net#open-roberta"

